In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
df = pd.read_csv("C:/Users/hp/Downloads/laptop.csv")
print(df)
df.head()

     Unnamed: 0                                              Model      Price  \
0             0  HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...    ₹50,399
1             1  Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...    ₹23,990
2             2  Lenovo V15 G4 ‎82YU00W7IN Laptop (AMD Ryzen 3 ...    ₹26,989
3             3  Samsung Galaxy Book2 Pro 13 Laptop (12th Gen C...    ₹69,990
4             4  Xiaomi Redmi G Pro 2024 Gaming Laptop (14th Ge...  ₹1,02,990
..          ...                                                ...        ...
915         915  Asus Vivobook 16X 2023 K3605ZF-MB541WS Laptop ...    ₹64,990
916         916  Asus TUF Gaming A15 2023 FA577XV-HQ036WS Gamin...  ₹1,54,990
917         917  Acer Aspire 5 A514-56GM Gaming Laptop (13th Ge...    ₹69,990
918         918  Lenovo IdeaPad Slim 5 82FG01B3IN Laptop (11th ...    ₹54,900
919         919  MSI Bravo 15 B5ED-034IN Gaming Laptop (AMD Ryz...    ₹59,990

     Rating                      Generation                             Core  \
0      70.0       5th Gen AMD Ryzen 5 5600H            Hexa Core, 12 Threads
1      56.0   11th Gen Intel Core i3 1115G4             Dual Core, 4 Threads
2      55.0       7th Gen AMD Ryzen 3 7320U             Quad Core, 8 Threads
3      60.0    12th Gen Intel Core i5 1240P   12 Cores (4P + 8E), 16 Threads
4      78.0  14th Gen Intel Core i9 14900HX  24 Cores (8P + 16E), 32 Threads
..      ...                             ...                              ...
915    68.0   12th Gen Intel Core i5 12450H  Octa Core (4P + 4E), 12 Threads
916     NaN      7th Gen AMD Ryzen 9 7940HS            Octa Core, 16 Threads
917    62.0    13th Gen Intel Core i7 1355U   10 Cores (2P + 8E), 12 Threads
918    63.0   11th Gen Intel Core i5 1135G7             Quad Core, 8 Threads
919    66.0       5th Gen AMD Ryzen 7 5800H            Octa Core, 16 Threads

                  Ram         SSD  \
0       8 GB DDR4 RAM  512 GB SSD
1     8 GB LPDDR4 RAM  512 GB SSD
2     8 GB LPDDR5 RAM  512 GB SSD
3    16 GB LPDDR5 RAM  512 GB SSD
4      16 GB DDR5 RAM    1 TB SSD
..                ...         ...
915    16 GB DDR4 RAM  512 GB SSD
916    16 GB DDR5 RAM    1 TB SSD
917     8 GB DDR4 RAM  512 GB SSD
918    16 GB DDR4 RAM  512 GB SSD
919     8 GB DDR4 RAM  512 GB SSD

                                           Display  \
0    15.6 inches, 1920 x 1080 pixels, Touch Screen
1                  15.6 inches, 1920 x 1080 pixels
2                  15.6 inches, 1920 x 1080 pixels
3                  13.3 inches, 1080 x 1920 pixels
4                  16.1 inches, 2560 x 1600 pixels
..                                             ...
915                  16 inches, 1920 x 1200 pixels
916                15.6 inches, 2560 x 1440 pixels
917                  14 inches, 1920 x 1080 pixels
918                15.6 inches, 1920 x 1080 pixels
919                15.6 inches, 1920 x 1080 pixels

                          Graphics             OS         Warranty
0         4 GB AMD Radeon RX 6500M  Windows 11 OS  1 Year Warranty
1               Intel UHD Graphics  Windows 11 OS  1 Year Warranty
2              AMD Radeon Graphics  Windows 11 OS  1 Year Warranty
3           Intel Iris Xe Graphics  Windows 11 OS  1 Year Warranty
4     8 GB NVIDIA GeForce RTX 4060  Windows 11 OS  1 Year Warranty
..                             ...            ...              ...
915   4 GB NVIDIA GeForce RTX 2050  Windows 11 OS  1 Year Warranty
916  8 GB NVIDIA GeForce RTX 4060   Windows 11 OS  1 Year Warranty
917   4 GB NVIDIA GeForce RTX 2050  Windows 11 OS  1 Year Warranty
918         Intel Iris Xe Graphics  Windows 11 OS  1 Year Warranty
919        4 GB AMD Radeon RX6500M  Windows 11 OS  1 Year Warranty

[920 rows x 12 columns]

,Unnamed: 0,Model,Price,Rating,Generation,Core,Ram,SSD,Display,Graphics,OS,Warranty
0,0,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,"₹50,399",70.0,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8 GB DDR4 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels, Touch Screen",4 GB AMD Radeon RX 6500M,Windows 11 OS,1 Year Warranty
1,1,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,"₹23,990",56.0,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8 GB LPDDR4 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1 Year Warranty
2,2,Lenovo V15 G4 ‎82YU00W7IN Laptop (AMD Ryzen 3 ...,"₹26,989",55.0,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon Graphics,Windows 11 OS,1 Year Warranty
3,3,Samsung Galaxy Book2 Pro 13 Laptop (12th Gen C...,"₹69,990",60.0,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16 GB LPDDR5 RAM,512 GB SSD,"13.3 inches, 1080 x 1920 pixels",Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty
4,4,Xiaomi Redmi G Pro 2024 Gaming Laptop (14th Ge...,"₹1,02,990",78.0,14th Gen Intel Core i9 14900HX,"24 Cores (8P + 16E), 32 Threads",16 GB DDR5 RAM,1 TB SSD,"16.1 inches, 2560 x 1600 pixels",8 GB NVIDIA GeForce RTX 4060,Windows 11 OS,1 Year Warranty

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  920 non-null    int64
 1   Model       920 non-null    object
 2   Price       920 non-null    object
 3   Rating      768 non-null    float64
 4   Generation  920 non-null    object
 5   Core        920 non-null    object
 6   Ram         920 non-null    object
 7   SSD         920 non-null    object
 8   Display     919 non-null    object
 9   Graphics    920 non-null    object
 10  OS          919 non-null    object
 11  Warranty    915 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 86.4+ KB

In [7]:
df.size

11040

In [8]:
df.shape

(920, 12)

In [9]:
df.ndim

2

In [10]:
df.describe

<bound method NDFrame.describe of      Unnamed: 0                                              Model      Price  \
0             0  HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...    ₹50,399
1             1  Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...    ₹23,990
2             2  Lenovo V15 G4 ‎82YU00W7IN Laptop (AMD Ryzen 3 ...    ₹26,989
3             3  Samsung Galaxy Book2 Pro 13 Laptop (12th Gen C...    ₹69,990
4             4  Xiaomi Redmi G Pro 2024 Gaming Laptop (14th Ge...  ₹1,02,990
..          ...                                                ...        ...
915         915  Asus Vivobook 16X 2023 K3605ZF-MB541WS Laptop ...    ₹64,990
916         916  Asus TUF Gaming A15 2023 FA577XV-HQ036WS Gamin...  ₹1,54,990
917         917  Acer Aspire 5 A514-56GM Gaming Laptop (13th Ge...    ₹69,990
918         918  Lenovo IdeaPad Slim 5 82FG01B3IN Laptop (11th ...    ₹54,900
919         919  MSI Bravo 15 B5ED-034IN Gaming Laptop (AMD Ryz...    ₹59,990

     Rating                      Generation                             Core  \
0      70.0       5th Gen AMD Ryzen 5 5600H            Hexa Core, 12 Threads
1      56.0   11th Gen Intel Core i3 1115G4             Dual Core, 4 Threads
2      55.0       7th Gen AMD Ryzen 3 7320U             Quad Core, 8 Threads
3      60.0    12th Gen Intel Core i5 1240P   12 Cores (4P + 8E), 16 Threads
4      78.0  14th Gen Intel Core i9 14900HX  24 Cores (8P + 16E), 32 Threads
..      ...                             ...                              ...
915    68.0   12th Gen Intel Core i5 12450H  Octa Core (4P + 4E), 12 Threads
916     NaN      7th Gen AMD Ryzen 9 7940HS            Octa Core, 16 Threads
917    62.0    13th Gen Intel Core i7 1355U   10 Cores (2P + 8E), 12 Threads
918    63.0   11th Gen Intel Core i5 1135G7             Quad Core, 8 Threads
919    66.0       5th Gen AMD Ryzen 7 5800H            Octa Core, 16 Threads

                  Ram         SSD  \
0       8 GB DDR4 RAM  512 GB SSD
1     8 GB LPDDR4 RAM  512 GB SSD
2     8 GB LPDDR5 RAM  512 GB SSD
3    16 GB LPDDR5 RAM  512 GB SSD
4      16 GB DDR5 RAM    1 TB SSD
..                ...         ...
915    16 GB DDR4 RAM  512 GB SSD
916    16 GB DDR5 RAM    1 TB SSD
917     8 GB DDR4 RAM  512 GB SSD
918    16 GB DDR4 RAM  512 GB SSD
919     8 GB DDR4 RAM  512 GB SSD

                                           Display  \
0    15.6 inches, 1920 x 1080 pixels, Touch Screen
1                  15.6 inches, 1920 x 1080 pixels
2                  15.6 inches, 1920 x 1080 pixels
3                  13.3 inches, 1080 x 1920 pixels
4                  16.1 inches, 2560 x 1600 pixels
..                                             ...
915                  16 inches, 1920 x 1200 pixels
916                15.6 inches, 2560 x 1440 pixels
917                  14 inches, 1920 x 1080 pixels
918                15.6 inches, 1920 x 1080 pixels
919                15.6 inches, 1920 x 1080 pixels

                          Graphics             OS         Warranty
0         4 GB AMD Radeon RX 6500M  Windows 11 OS  1 Year Warranty
1               Intel UHD Graphics  Windows 11 OS  1 Year Warranty
2              AMD Radeon Graphics  Windows 11 OS  1 Year Warranty
3           Intel Iris Xe Graphics  Windows 11 OS  1 Year Warranty
4     8 GB NVIDIA GeForce RTX 4060  Windows 11 OS  1 Year Warranty
..                             ...            ...              ...
915   4 GB NVIDIA GeForce RTX 2050  Windows 11 OS  1 Year Warranty
916  8 GB NVIDIA GeForce RTX 4060   Windows 11 OS  1 Year Warranty
917   4 GB NVIDIA GeForce RTX 2050  Windows 11 OS  1 Year Warranty
918         Intel Iris Xe Graphics  Windows 11 OS  1 Year Warranty
919        4 GB AMD Radeon RX6500M  Windows 11 OS  1 Year Warranty

[920 rows x 12 columns]>

In [11]:
df.isnull()

,Unnamed: 0,Model,Price,Rating,Generation,Core,Ram,SSD,Display,Graphics,OS,Warranty
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
915,False,False,False,False,False,False,False,False,False,False,False,False
916,False,False,False,True,False,False,False,False,False,False,False,False
917,False,False,False,False,False,False,False,False,False,False,False,False
918,False,False,False,False,False,False,False,False,False,False,False,False
919,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.isnull().sum()

Unnamed: 0      0
Model           0
Price           0
Rating        152
Generation      0
Core            0
Ram             0
SSD             0
Display         1
Graphics        0
OS              1
Warranty        5
dtype: int64

In [13]:
for i in df.columns:
    if df[i].dtype == "object":
        df[i] = df[i].fillna(df[i].mode()[0])
    else:
        df[i] = df[i].fillna(df[i].mean())
df.isnull().sum()

Unnamed: 0    0
Model         0
Price         0
Rating        0
Generation    0
Core          0
Ram           0
SSD           0
Display       0
Graphics      0
OS            0
Warranty      0
dtype: int64

In [14]:
print("Before dupliacates:",df.shape)
df = df.drop_duplicates()
print("After duplicates:",df.shape)

Before dupliacates: (920, 12)
After duplicates: (920, 12)

In [15]:
def clean_price(x):
    x = str(x)
    x = x.replace('₹', '')
    x = x.replace(',', '')
    return float(x)


df['Price'] = df['Price'].apply(clean_price)

In [16]:
import re

In [17]:
def extract_ram(x):
    match = re.search(r'(\d+)', str(x))
    return int(match.group(1)) if match else np.nan


df['RAM_GB'] = df['Ram'].apply(extract_ram)

In [18]:
def extract_ssd(x):
    x = str(x)

    if 'TB' in x:
        num = float(re.search(r'(\d+\.?\d*)', x).group(1))
        return int(num * 1024)

    elif 'GB' in x:
        num = float(re.search(r'(\d+\.?\d*)', x).group(1))
        return int(num)

    return np.nan


df['SSD_GB'] = df['SSD'].apply(extract_ssd)

In [19]:
def extract_screen_size(x):
    match = re.search(r'(\d+\.?\d*)', str(x))
    return float(match.group(1)) if match else np.nan


df['Screen_Size'] = df['Display'].apply(extract_screen_size)

In [20]:
df['Brand'] = df['Model'].apply(lambda x: str(x).split()[0])

In [21]:
def processor_brand(x):
    x = str(x).lower()

    if 'intel' in x:
        return 'Intel'

    elif 'ryzen' in x or 'amd' in x:
        return 'AMD'

    elif 'apple' in x:
        return 'Apple'

    return 'Other'


df['Processor_Brand'] = df['Generation'].apply(processor_brand)

In [22]:
df['Price'] = (
    df['Price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

In [23]:
df.head()

,Unnamed: 0,Model,Price,Rating,Generation,Core,Ram,SSD,Display,Graphics,OS,Warranty,RAM_GB,SSD_GB,Screen_Size,Brand,Processor_Brand
0,0,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,50399.0,70.0,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8 GB DDR4 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels, Touch Screen",4 GB AMD Radeon RX 6500M,Windows 11 OS,1 Year Warranty,8,512.0,15.6,HP,AMD
1,1,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,23990.0,56.0,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8 GB LPDDR4 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1 Year Warranty,8,512.0,15.6,Tecno,Intel
2,2,Lenovo V15 G4 ‎82YU00W7IN Laptop (AMD Ryzen 3 ...,26989.0,55.0,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon Graphics,Windows 11 OS,1 Year Warranty,8,512.0,15.6,Lenovo,AMD
3,3,Samsung Galaxy Book2 Pro 13 Laptop (12th Gen C...,69990.0,60.0,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16 GB LPDDR5 RAM,512 GB SSD,"13.3 inches, 1080 x 1920 pixels",Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty,16,512.0,13.3,Samsung,Intel
4,4,Xiaomi Redmi G Pro 2024 Gaming Laptop (14th Ge...,102990.0,78.0,14th Gen Intel Core i9 14900HX,"24 Cores (8P + 16E), 32 Threads",16 GB DDR5 RAM,1 TB SSD,"16.1 inches, 2560 x 1600 pixels",8 GB NVIDIA GeForce RTX 4060,Windows 11 OS,1 Year Warranty,16,1024.0,16.1,Xiaomi,Intel

In [24]:
Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[
    (df['Price'] >= lower) &
    (df['Price'] <= upper)
]

In [25]:
if 'Unnamed: 0' in df.columns:
    df.drop('Unnamed: 0', axis=1, inplace=True)

In [26]:
features = [
    'Brand',
    'Rating',
    'Generation',
    'Core',
    'Graphics',
    'OS',
    'RAM_GB',
    'SSD_GB',
    'Screen_Size',
    'Processor_Brand'
]

X = df[features]
y = df['Price']

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [29]:
cat_cols = X.select_dtypes(include='object').columns
num_cols = X.select_dtypes(exclude='object').columns

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [31]:
numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, num_cols),
    ('cat', categorical_transformer, cat_cols)
])

In [32]:
from xgboost import XGBRegressor

In [33]:
model = XGBRegressor(
    n_estimators=1500,
    learning_rate=0.01,
    max_depth=10,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)

In [34]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', model)
])

In [35]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['Rating', 'RAM_GB', 'SSD_GB', 'Screen_Size'], dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Brand', 'Generat...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.01,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=10, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=1500, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [36]:
y_pred = pipeline.predict(X_test)

In [37]:
from sklearn.metrics import r2_score, mean_absolute_error

In [38]:
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R2 Score:", r2)
print("MAE:", mae)

R2 Score: 0.8444145003647039
MAE: 8835.138920349482

In [39]:
import pickle

pickle.dump(pipeline, open('laptop_price_model.pkl', 'wb'))

In [40]:

import pandas as pd
import numpy as np
import re
import pickle
import gradio as gr

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import r2_score

from xgboost import XGBRegressor

df = pd.read_csv("C:/Users/hp/Downloads/laptop.csv")
print("Duplicates:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
df['Price'] = (
    df['Price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

df.dropna(subset=['Price'], inplace=True)


def extract_ram(x):
    match = re.search(r'(\d+)', str(x))
    return int(match.group(1)) if match else np.nan


df['RAM_GB'] = df['Ram'].apply(extract_ram)

def extract_ssd(x):
    x = str(x)

    if 'TB' in x:
        num = float(re.search(r'(\d+\.?\d*)', x).group(1))
        return int(num * 1024)

    elif 'GB' in x:
        num = float(re.search(r'(\d+\.?\d*)', x).group(1))
        return int(num)

    return np.nan


df['SSD_GB'] = df['SSD'].apply(extract_ssd)

def extract_screen(x):
    match = re.search(r'(\d+\.?\d*)', str(x))
    return float(match.group(1)) if match else np.nan


df['Screen_Size'] = df['Display'].apply(extract_screen)

df['Brand'] = df['Model'].apply(lambda x: str(x).split()[0])


def processor_brand(x):
    x = str(x).lower()

    if 'intel' in x:
        return 'Intel'

    elif 'amd' in x or 'ryzen' in x:
        return 'AMD'

    elif 'apple' in x:
        return 'Apple'

    return 'Other'


df['Processor_Brand'] = df['Generation'].apply(processor_brand)

Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['Price'] >= lower) & (df['Price'] <= upper)]

features = [
    'Brand',
    'Rating',
    'Generation',
    'Core',
    'Graphics',
    'OS',
    'RAM_GB',
    'SSD_GB',
    'Screen_Size',
    'Processor_Brand'
]

X = df[features]
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

cat_cols = X.select_dtypes(include='object').columns
num_cols = X.select_dtypes(exclude='object').columns

numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, num_cols),
    ('cat', categorical_transformer, cat_cols)
])

model = XGBRegressor(
    n_estimators=1500,
    learning_rate=0.01,
    max_depth=10,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', model)
])

pipeline.fit(X_train, y_train)

predictions = pipeline.predict(X_test)

score = r2_score(y_test, predictions)

print("R2 Score:", score)

pickle.dump(pipeline, open('laptop_model.pkl', 'wb'))

def predict_price(
    brand,
    rating,
    generation,
    core,
    graphics,
    os_name,
    ram,
    ssd,
    screen,
    processor_brand
):

    input_data = pd.DataFrame({
        'Brand': [brand],
        'Rating': [rating],
        'Generation': [generation],
        'Core': [core],
        'Graphics': [graphics],
        'OS': [os_name],
        'RAM_GB': [ram],
        'SSD_GB': [ssd],
        'Screen_Size': [screen],
        'Processor_Brand': [processor_brand]
    })

    prediction = pipeline.predict(input_data)[0]

    return f'Estimated Laptop Price: ₹ {round(prediction, 2)}'

app = gr.Interface(
    fn=predict_price,

    inputs=[
        gr.Dropdown(df['Brand'].dropna().unique().tolist(), label='Brand'),
        gr.Slider(1, 5, step=0.1, label='Rating'),
        gr.Textbox(label='Generation'),
        gr.Textbox(label='Core'),
        gr.Textbox(label='Graphics'),
        gr.Dropdown(df['OS'].dropna().unique().tolist(), label='Operating System'),
        gr.Slider(2, 64, step=2, label='RAM (GB)'),
        gr.Slider(128, 4096, step=128, label='SSD (GB)'),
        gr.Slider(11, 18, step=0.1, label='Screen Size'),
        gr.Dropdown(['Intel', 'AMD', 'Apple', 'Other'], label='Processor Brand')
    ],

    outputs=gr.Textbox(label='Predicted Price'),

    title='Laptop Price Prediction App',

    description='Predict laptop price using Machine Learning and XGBoost'
)

app.launch()

Duplicates: 0
R2 Score: 0.835124135017395
* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.